spring:
  application:
    name: provider
dubbo:
  registry:
    address: nacos://192.168.0.107:8848
    protocol: rmi
    timeout: 6000
  protocols: { dubbo1: {name: dubbo, port: 20080, accesslog: "true"}, rmi: {name: rmi, port: 20081}}
