spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        filters:
          - StripPrefix=1
    nacos:
      discovery:
        server-addr: 192.168.0.107:8848
server:
  port: 9000




