spring:
  application:
    name: comsumer-Server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.107:8848
dubbo:
  registry:
    address: nacos://192.168.0.107:8848
    check: false
    timeout: 6000




